global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'gateway:7000' ]
  - job_name: "messenger"
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'messenger:7001' ]
  - job_name: "auth"
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth:7002']
  - job_name: "users"
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'users:7003' ]